package project.spring.enums;

public enum StatusPagamento {

	  	PENDING,
	    RECEIVED,
	    CONFIRMED,
	    OVERDUE,
	    REFUNDED,
	    RECEIVED_IN_CASH,
	    REFUND_REQUESTED,
	    REFUND_IN_PROGRESS,
	    CHARGEBACK_REQUESTED,
	    CHARGEBACK_DISPUTE,
	    AWAITING_CHARGEBACK_REVERSAL,
	    DUNNING_RECEIVED,
	    DUNNING_REQUESTED,
	    BANK_SLIP_VIEWED,
	    CHECKOUT_VIEWED,
	    SPLIT_DIVERGENCE_BLOCK,
	    SPLIT_DIVERGENCE_BLOCK_FINISHED;
	
	
	
}


